- name: Setup local
  hosts: localhost
  roles:
    - role: base
      tags:
        - base
    - role: git
      tags:
        - git
    - role: terminal
      tags:
        - terminal
    - role: asdf
      tags:
        - asdf
