- name: Install git
  become: true
  apt:
    name:
      - git
      - libsecret-1-dev
      - libsecret-1-0
      - meld
    state: present
    update_cache: true
    cache_valid_time: "3600"

- name: Copy global gitconfig
  template:
    src: ".gitconfig_global.j2"
    dest: "{{ dotfiles_user_home }}/.gitconfig"
    mode: "0644"

- name: Copy global gitignore
  copy:
    src: "files/.gitignore_global"
    dest: "{{ dotfiles_user_home }}/.gitignore_global"
    mode: "0644"
