- name: Setup local
  hosts: localhost
  roles:
    - role: base
      tags:
        - base
    - role: git
      tags:
        - git
    - role: fish
      tags:
        - fish
    - role: asdf
      tags:
        - asdf
